name: me
channels:
#  - postelrich
  - conda-forge
dependencies:
  - python>3.5
  - numpy
  - simpleitk>2.0
  - matplotlib
  - nibabel
  - integv
#  - pip
#  - pip:
#    - yahoo_fin
#    - yfinance
#    - yahoo-finance
#    - fix-yahoo-finance
# conda env create -f environment.yml
# activate and ->conda env update --file local.yml --prune
#or
# conda env update --name myenv --file local.yml --prune


